#!/usr/bin/env bash
# lib/core.sh - Execution engine for glue

glue_dispatch() {
    local action="$1"
    shift

    # Load configuration and resolve backend if not already done
    glue_load_config
    glue_resolve_backend || return 1

    local backend="$GLUE_ACTIVE_BACKEND"
    local backend_fn="glue_backend_${backend}"

    if ! declare -f "$backend_fn" >/dev/null 2>&1; then
        echo "Error: Backend function '$backend_fn' is not defined." >&2
        return 1
    fi

    # Execute backend function to populate GLUE_CMD_SUDO and GLUE_CMD_ARGS
    "$backend_fn" "$action" "$@" || return 1

    local cmd=("${GLUE_CMD_ARGS[@]}")

    if [[ ${#cmd[@]} -eq 0 ]]; then
        echo "Error: No command generated by backend '$backend' for action '$action'." >&2
        return 1
    fi

    # Determine whether sudo is needed
    local exec_cmd=()
    if [[ "${GLUE_CMD_SUDO:-false}" == "true" && "$(id -u 2>/dev/null)" -ne 0 ]]; then
        exec_cmd=("sudo" "${cmd[@]}")
    else
        exec_cmd=("${cmd[@]}")
    fi

    local cmd_str="${exec_cmd[*]}"

    if [[ "${GLUE_VERBOSE:-false}" == "true" || "${GLUE_VERBOSE:-false}" == "1" ]]; then
        echo "[glue] ($backend) $cmd_str" >&2
    fi

    if [[ "${GLUE_DRY_RUN:-false}" == "true" || "${GLUE_DRY_RUN:-false}" == "1" ]]; then
        echo "$cmd_str"
        return 0
    fi

    # Execute the command
    "${exec_cmd[@]}"
}
