#!/usr/bin/env bash
# lib/core.sh - Execution engine for glue

glue_dispatch() {
    # Load configuration
    glue_load_config

    local dry_run_override=""
    local verbose_override=""
    local backend_override=""
    local clean_args=()

    # Parse global options passed as arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run)
                dry_run_override="true"
                shift
                ;;
            --verbose|-v)
                verbose_override="true"
                shift
                ;;
            --backend=*)
                backend_override="${1#*=}"
                shift
                ;;
            *)
                clean_args+=("$1")
                shift
                ;;
        esac
    done

    # Restore positional arguments without global flags
    set -- "${clean_args[@]}"

    local action="${1:-}"
    shift 2>/dev/null || true

    if [[ -z "$action" ]]; then
        echo "Error: No action specified for glue dispatch." >&2
        return 1
    fi

    # Apply overrides if provided
    if [[ -n "$dry_run_override" ]]; then
        GLUE_DRY_RUN="$dry_run_override"
    fi
    if [[ -n "$verbose_override" ]]; then
        GLUE_VERBOSE="$verbose_override"
    fi
    if [[ -n "$backend_override" ]]; then
        GLUE_BACKEND="$backend_override"
    fi

    glue_resolve_backend || return 1

    local backend="$GLUE_ACTIVE_BACKEND"

    # Package name mapping hook (v2.0)
    local target_pkgs=()
    if declare -f glue_map_packages >/dev/null 2>&1 && [[ "$action" =~ ^(install|remove|show|search)$ ]]; then
        read -r -a target_pkgs <<< "$(glue_map_packages "$backend" "$@")"
        set -- "${target_pkgs[@]}"
    fi

    local backend_fn="glue_backend_${backend}"

    if ! declare -f "$backend_fn" >/dev/null 2>&1; then
        echo "Error: Backend function '$backend_fn' is not defined." >&2
        return 1
    fi

    # Execute backend function to populate GLUE_CMD_SUDO and GLUE_CMD_ARGS
    "$backend_fn" "$action" "$@" || return 1

    local cmd=("${GLUE_CMD_ARGS[@]}")

    if [[ ${#cmd[@]} -eq 0 ]]; then
        echo "Error: No command generated by backend '$backend' for action '$action'." >&2
        return 1
    fi

    # Determine whether sudo is needed
    local exec_cmd=()
    if [[ "${GLUE_CMD_SUDO:-false}" == "true" && "$(id -u 2>/dev/null)" -ne 0 ]]; then
        exec_cmd=("sudo" "${cmd[@]}")
    else
        exec_cmd=("${cmd[@]}")
    fi

    local cmd_str="${exec_cmd[*]}"

    if [[ "${GLUE_VERBOSE:-false}" == "true" || "${GLUE_VERBOSE:-false}" == "1" ]]; then
        echo "[glue] ($backend) $cmd_str" >&2
    fi

    if [[ "${GLUE_DRY_RUN:-false}" == "true" || "${GLUE_DRY_RUN:-false}" == "1" ]]; then
        echo "$cmd_str"
        return 0
    fi

    # Execute the command
    "${exec_cmd[@]}"
}
